on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2       
    - name: Install deps (ubuntu)
      run: sudo apt-get install -y libasound2-dev
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: test (core)
      run: cargo test
      working-directory: ./core
    - name: clippy (core)
      run: cargo clippy
      working-directory: ./core
    - name: install dependencies (ui)
      run: npm install
      working-directory: ./ui
    - name: test (ui)
      run: npm test
      working-directory: ./ui
    - name: make (ui)
      run: npm run prod:make
      working-directory: ./ui
    - uses: actions/upload-artifact@v2
      with:
        name: app-${{matrix.os}}
        path: ui/out/make/**/*.zip
